### ISSUE TITLE
Internal Server Error on Sign Up page

### ISSUE THREAD

**Issue by raxp122** [quoctran98/Wiki-Wall-Street#3]
This is the error i get if i try to sign up:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by raxp122** [comment]
Just noticed that in the file models.py in the function check_password in the return there is a missing ")" at the end, maybe that's causing the issue in the registration process

Edit:
i modified line 35 (by removing method as it's not required) to: return check_password_hash(self.password, password) and it works on my pc locally

**Comment by quoctran98** [comment]
Should maybe work now?  Mainly a dependency issue that I've been too lazy to fix.
